name: Build INAV (SPEEDYBEEF405WING)

on:
  workflow_dispatch:
  push:
    paths:
      - "src/**"
      - "cmake/**"
      - ".github/workflows/inav-build.yml"

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake xz-utils

      - name: Configure CMake (arm-none-eabi)
        run: |
          rm -rf build
          mkdir -p build
          cd build
          # TOOLCHAIN=arm-none-eabi tells INAV’s CMake to auto-download the correct ARM toolchain
          cmake .. -G Ninja -DTOOLCHAIN=arm-none-eabi

      - name: (Debug) list SPEEDYBEEF405WING targets
        run: |
          cd build
          ninja -t targets all | grep -i SPEEDYBEEF405WING || true

      - name: Build firmware (.bin)
        run: |
          cd build
          # Build the .bin target directly (this exists even if the .elf is not a top-level target)
          cmake --build . --target src/main/target/SPEEDYBEEF405WING/SPEEDYBEEF405WING.bin -j"$(nproc)"

      - name: Collect artifacts
        run: |
          mkdir -p out
          cp -v build/src/main/target/SPEEDYBEEF405WING/SPEEDYBEEF405WING.bin out/
          # Grab extra files if they exist (not required)
          [ -f build/src/main/target/SPEEDYBEEF405WING/SPEEDYBEEF405WING.elf ] && cp -v build/src/main/target/SPEEDYBEEF405WING/SPEEDYBEEF405WING.elf out/
          [ -f build/src/main/target/SPEEDYBEEF405WING/SPEEDYBEEF405WING.map ] && cp -v build/src/main/target/SPEEDYBEEF405WING/SPEEDYBEEF405WING.map out/

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: inav-SPEEDYBEEF405WING-${{ github.sha }}
          path: out/*
