name: Build INAV SpeedyBeeF405Wing

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build git wget xz-utils

      - name: Install ARM toolchain
        run: |
          wget https://developer.arm.com/-/media/Files/downloads/gnu/13.2.rel1/binrel/arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi.tar.xz
          tar -xf arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi.tar.xz
          echo "$PWD/arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi/bin" >> $GITHUB_PATH

      - name: Configure build
        run: |
          mkdir -p build
          cmake -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DTARGET=SPEEDYBEEF405WING \
            -DFORCE_BOOTLOADER_BUILD=ON \
            -DCMAKE_C_FLAGS_RELEASE="-O2 -g0 -flto" \
            -DCMAKE_CXX_FLAGS_RELEASE="-O2 -g0 -flto"

      - name: Build ELF and BIN
        run: |
          cmake --build build --target SPEEDYBEEF405WING_for_bl.elf -j$(nproc)
          cmake --build build --target SPEEDYBEEF405WING_for_bl.bin -j$(nproc)

      - name: Generate HEX from ELF
        run: |
          arm-none-eabi-objcopy -O ihex \
            build/bin/SPEEDYBEEF405WING_for_bl.elf \
            build/bin/SPEEDYBEEF405WING_for_bl.hex

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: inav-speedybeef405wing-build
          path: |
            build/bin/SPEEDYBEEF405WING_for_bl.elf
            build/bin/SPEEDYBEEF405WING_for_bl.bin
            build/bin/SPEEDYBEEF405WING_for_bl.hex
