name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake xz-utils

      - name: Configure (enable LTO)
        run: |
          rm -rf build
          mkdir -p build
          cd build
          cmake .. -G Ninja -DTOOLCHAIN=arm-none-eabi \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_C_FLAGS_RELWITHDEBINFO="-Os -flto" \
            -DCMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO="-flto"

      - name: Build (for bootloader slot)
        run: |
          cmake --build build --target src/main/target/SPEEDYBEEF405WING/SPEEDYBEEF405WING_for_bl.elf -j$(nproc)

      - name: Make BIN/HEX
        run: |
          arm-none-eabi-objcopy -O binary \
            build/bin/SPEEDYBEEF405WING_for_bl.elf \
            build/inav_SPEEDYBEEF405WING_for_bl.bin
          arm-none-eabi-objcopy -O ihex \
            build/bin/SPEEDYBEEF405WING_for_bl.elf \
            build/inav_SPEEDYBEEF405WING_for_bl.hex

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: inav-speedybee-forbl-lto
          path: |
            build/inav_SPEEDYBEEF405WING_for_bl.bin
            build/inav_SPEEDYBEEF405WING_for_bl.hex
