name: SpeedybeeBuild

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake xz-utils

      - name: Configure CMake (downloads toolchain automatically)
        run: |
          rm -rf build
          mkdir -p build
          cmake -S . -B build -G Ninja -DTOOLCHAIN=arm-none-eabi

      - name: Build SPEEDYBEEF405WING ELF
        run: |
          cmake --build build --target src/main/target/SPEEDYBEEF405WING/SPEEDYBEEF405WING.elf -j$(nproc)

      - name: Make HEX and BIN from ELF
        run: |
          TOOLBIN="${{ github.workspace }}/tools/arm-gnu-toolchain-13.2.rel1/bin"
          ELF="build/src/main/target/SPEEDYBEEF405WING/SPEEDYBEEF405WING.elf"
          mkdir -p build/artifacts
          "$TOOLBIN/arm-none-eabi-objcopy" -O ihex    "$ELF" "build/artifacts/SPEEDYBEEF405WING.hex"
          "$TOOLBIN/arm-none-eabi-objcopy" -O binary  "$ELF" "build/artifacts/SPEEDYBEEF405WING.bin"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SPEEDYBEEF405WING
          path: build/artifacts/*
