name: INAV Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake git wget xz-utils

      - name: Build SPEEDYBEEF405WING firmware
        run: |
          mkdir -p build
          cd build
          cmake .. -G Ninja -DTOOLCHAIN=arm-none-eabi
          ninja inav_SPEEDYBEEF405WING

      - name: Upload HEX file
        uses: actions/upload-artifact@v3
        with:
          name: SPEEDYBEEF405WING-firmware
          path: build/obj/SPEEDYBEEF405WING/inav_SPEEDYBEEF405WING.hex
