name: Build INAV SpeedyBeeF405Wing

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build git wget xz-utils

      - name: Configure build
        run: |
          mkdir -p build
          cmake -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DTARGET=SPEEDYBEEF405WING \
            -DFORCE_BOOTLOADER_BUILD=ON \
            -DCMAKE_C_FLAGS_RELEASE="-O2 -g0" \
            -DCMAKE_CXX_FLAGS_RELEASE="-O2 -g0"

      - name: Build ELF
        run: |
          cmake --build build --target SPEEDYBEEF405WING_for_bl.elf -j$(nproc)

      - name: Build BIN
        run: |
          cmake --build build --target SPEEDYBEEF405WING_for_bl.bin -j$(nproc)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: inav-speedybeef405wing-build
          path: |
            build/bin/SPEEDYBEEF405WING_for_bl.elf
            build/bin/SPEEDYBEEF405WING_for_bl.bin
