name: Build INAV (SPEEDYBEEF405WING)

on:
  workflow_dispatch:
  push:
    paths:
      - "src/**"
      - "cmake/**"
      - ".github/workflows/inav-build.yml"

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake xz-utils

      - name: Configure CMake (arm-none-eabi)
        run: |
          rm -rf build
          mkdir -p build
          cd build
          cmake .. -G Ninja -DTOOLCHAIN=arm-none-eabi

      - name: Build SPEEDYBEEF405WING
        run: |
          cd build
          # Build the .bin (this implicitly builds the .elf too)
          cmake --build . --target src/main/target/SPEEDYBEEF405WING/SPEEDYBEEF405WING.bin -j"$(nproc)"

      - name: Collect artifacts
        run: |
          mkdir -p out
          # INAV places the final .bin at the repo root's build/ with version in the name
          cp -v build/inav_*_SPEEDYBEEF405WING.bin out/
          # The .elf is in build/bin/
          cp -v build/bin/SPEEDYBEEF405WING.elf out/ || true
          # Optional: map / listing
          ls -la build | sed -n '1,200p'
          ls -la out

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: inav-SPEEDYBEEF405WING-${{ github.sha }}
          path: out/*
